import {createHash} from 'node:crypto';
import {validateTopology} from './topology.mjs';
const hash=text=>createHash('sha256').update(String(text)).digest('hex');
export function createReadingGraph({game,sources,entities=[]}){
 const sourceMap=new Map(),blocks=new Map(),evidenceMap=new Map(),claimMap=new Map();
 for(const source of sources){if(sourceMap.has(source.id))throw Error('Duplicate source '+source.id);sourceMap.set(source.id,source);for(const block of source.blocks){const key=source.id+'#'+block.id;if(blocks.has(key))throw Error('Duplicate block '+key);blocks.set(key,block);}}
 const entityMap=new Map();for(const e of entities){if(entityMap.has(e.id))throw Error('Duplicate entity '+e.id);entityMap.set(e.id,e);}
 function evidence(ref){const source=sourceMap.get(ref.sourceId);if(!source)throw Error('Missing source '+ref.sourceId);const matches=source.blocks.filter(b=>(!ref.field||b.field===ref.field)&&(!ref.anchor||b.anchor===ref.anchor)&&(!ref.hash||b.hash===ref.hash)&&b.text.includes(ref.quote));if(!matches.length)throw Error('Quote does not match source '+ref.sourceId);const block=matches[0];if(ref.sourceSha256&&ref.sourceSha256!==block.sha256)throw Error('Source hash differs '+ref.sourceId);const id='evidence-'+hash(source.id+'|'+block.id+'|'+ref.quote).slice(0,20);evidenceMap.set(id,{id,sourceId:source.id,blockId:block.id,quote:ref.quote,url:block.url,title:ref.title||source.title,speaker:ref.speaker||'',sourceSha256:block.sha256||hash(block.text)});return id;}
 function claim(text,refs,{kind='explicit',speaker=''}={}){if(!refs?.length)throw Error('Claim needs source evidence');if(!['explicit','attributed','inference'].includes(kind))throw Error('Unknown claim kind');const evidenceIds=refs.map(evidence);const id='claim-'+hash(text+'|'+kind+'|'+speaker+'|'+evidenceIds.join('|')).slice(0,20);claimMap.set(id,{id,text,kind,speaker,evidenceIds});return id;}
 function output({clusters=[],relations=[],events=[]}){const ids=new Set();for(const c of clusters){for(const t of [c.topology,...(c.views||[])].filter(Boolean))validateTopology(t,id=>claimMap.has(id));if(ids.has(c.id))throw Error('Duplicate cluster '+c.id);ids.add(c.id);if(!entityMap.has(c.entityId))throw Error('Missing cluster entity '+c.entityId);for(const s of c.sections||[])for(const id of s.claimIds)if(!claimMap.has(id))throw Error('Missing section claim '+id);}for(const r of relations){if(!entityMap.has(r.from)||!entityMap.has(r.to))throw Error('Missing relation endpoint');if(!claimMap.has(r.reasonClaimId))throw Error('Missing relation reason');}for(const e of events)if(!claimMap.has(e.claimId))throw Error('Missing event claim');return {schema:'game-reading.v1',game,sources:sources.map(s=>({id:s.id,title:s.title,kind:s.kind,url:s.url,blocks:s.blocks.map(b=>({id:b.id,url:b.url,field:b.field,anchor:b.anchor,length:b.text.length,sha256:b.sha256||hash(b.text),locator:b.locator}))})),entities,claims:[...claimMap.values()],evidence:[...evidenceMap.values()],relations,events,clusters};}
 return {claim,evidence,output};
}
export function resolveCluster(graph,id){const cluster=graph.clusters.find(c=>c.id===id);if(!cluster)throw Error('Missing cluster '+id);const claimMap=new Map(graph.claims.map(c=>[c.id,c])),evidenceMap=new Map(graph.evidence.map(e=>[e.id,e])),entityMap=new Map(graph.entities.map(e=>[e.id,e]));const item=id=>{const c=claimMap.get(id);return {...c,evidence:c.evidenceIds.map(id=>evidenceMap.get(id))};};const topology=t=>({...t,edges:t.edges.map(e=>({...e,...item(e.claimId),id:e.id,kind:e.kind||'relation',claimKind:item(e.claimId).kind,reason:item(e.claimId).text}))});return {...cluster,topology:cluster.topology?topology(cluster.topology):null,views:(cluster.views||[]).map(topology),sections:cluster.sections.map(s=>({...s,items:s.claimIds.map(item)})),relations:graph.relations.filter(r=>r.clusterId===id).map(r=>({...r,from:entityMap.get(r.from),to:entityMap.get(r.to),reason:item(r.reasonClaimId).text,claimKind:item(r.reasonClaimId).kind,speaker:item(r.reasonClaimId).speaker,evidence:item(r.reasonClaimId).evidence})),events:graph.events.filter(e=>e.clusterId===id).map(e=>({...e,...item(e.claimId)}))};}
