import {renderTopology,topologyFromRelations} from './topology.mjs';
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeHref(value){const s=String(value);if(!/^(?:https?:\/\/|\/|#)/.test(s)||s.startsWith('//'))throw Error('Unsupported reading URL');return escapeHtml(s);}
export function paragraphRuns(value){return String(value).split(/(\n\s*\n)/).reduce((out,text,i)=>{if(i%2)out[out.length-1].separator=text;else out.push({text,separator:''});return out;},[]);}
export function createReadingKit({inline=escapeHtml,evidence=()=>''}={}){
 const E=escapeHtml,link=n=>`<a class="rw-target" data-reading-link href="${safeHref(n.url)}"><small>${E(n.kind||'')}</small><strong>${E(n.name)}</strong></a>`;
 const proof=items=>items?.length?`<details class="rw-proof"><summary>원문 근거 ${items.length}</summary>${evidence(items)}</details>`:'';
 const section=s=>`<section class="rw-section" id="${E(s.id)}"><header><h2>${E(s.title)}</h2>${s.deck?`<p class="rw-deck">${E(s.deck)}</p>`:''}</header>${s.items.map(item=>`<article class="rw-reading-unit">${item.title?`<h3>${E(item.title)}</h3>`:''}${item.kind==='inference'?'<span class="rw-attribution">편집자의 해석</span>':item.speaker?`<span class="rw-attribution">${E(item.speaker)}</span>`:''}<p>${inline(item.text)}</p>${proof(item.evidence)}</article>`).join('')}</section>`;
 const relations=items=>`<div class="rw-relations">${items.map(r=>`<article class="rw-relation"><div class="rw-edge">${link(r.from)}<div class="rw-verb"><strong>${E(r.label)}</strong><span aria-hidden="true">→</span></div>${link(r.to)}</div><p>${inline(r.reason)}</p>${r.kind==='inference'?'<span class="rw-attribution">편집자의 연결</span>':''}${proof(r.evidence)}</article>`).join('')}</div>`;
 const timeline=(items,{ordered=false,note=''}={})=>`<div class="rw-timeline" data-order="${ordered?'source':'independent'}">${note?`<p class="rw-deck">${E(note)}</p>`:''}<ol>${items.map(item=>`<li><span class="rw-time">${E(item.when||'')}</span><div><h3>${E(item.title)}</h3><p>${inline(item.text)}</p>${proof(item.evidence)}</div></li>`).join('')}</ol></div>`;
 const comparison=panels=>`<div class="rw-comparison">${panels.map(p=>`<article><header><h3>${E(p.title)}</h3>${p.speaker?`<span class="rw-attribution">${E(p.speaker)}</span>`:''}</header><p>${inline(p.text)}</p>${proof(p.evidence)}</article>`).join('')}</div>`;
 const containment=c=>`<div class="rw-containment"><strong>${E(c.parent)}</strong><ul>${c.children.map(n=>`<li>${typeof n==='string'?E(n):link(n)}</li>`).join('')}</ul>${proof(c.evidence)}</div>`;
 const process=(items,{kind='steps',label='',returnLabel=''}={})=>{if(kind==='cycle'&&!returnLabel)throw Error('Cycle needs an evidenced return label');return `<section class="rw-process" data-kind="${E(kind)}">${label?`<h2>${E(label)}</h2>`:''}<ol>${items.map(item=>`<li><h3>${E(item.title)}</h3><p>${inline(item.text)}</p>${proof(item.evidence)}</li>`).join('')}</ol>${kind==='cycle'?`<p class="rw-return">↺ ${E(returnLabel)}</p>`:''}</section>`;};
 const source=blocks=>`<div class="rw-original">${blocks.map(block=>`<section id="${E(block.id)}">${block.title?`<h2>${E(block.title)}</h2>`:''}${paragraphRuns(block.text).map(p=>`<p>${E(p.text)}</p>`).join('')}</section>`).join('')}</div>`;
 const topology=t=>renderTopology(t,{escape:E,href:safeHref,inline,evidence});
 const network=(items,options)=>{const t=topologyFromRelations(items,options);return t?topology(t):'';};
 return {section,relations,timeline,comparison,containment,process,source,topology,network};
}
