(()=>{
 const base='/wuwa-quests',path=location.pathname;let point;try{point=JSON.parse(sessionStorage.getItem('wuwa-reading-return')||'null');}catch{}
 let from;try{const value=new URLSearchParams(location.search).get('from');if(value?.startsWith(base+'/')){const url=new URL(value,location.origin);if(url.origin===location.origin&&url.pathname.startsWith(base+'/')&&url.pathname!==path)from=url.pathname+url.search+url.hash;}}catch{}
 if(from){const bar=document.createElement('aside'),a=document.createElement('a');bar.className='reading-return';bar.setAttribute('aria-label','이전 자료');a.href=from;a.textContent='← 읽던 자료로 돌아가기';bar.append(a);document.querySelector('main')?.prepend(bar);}
 else if(point&&/^\/wuwa-quests\/quests\/\d+\.html(?:#[\w-]+)?$/.test(point.path)&&!path.includes('/quests/')){const bar=document.createElement('aside'),a=document.createElement('a');bar.className='reading-return';bar.setAttribute('aria-label','읽던 대사');a.href=point.path;a.textContent='← '+point.title+' · 읽던 대사로 돌아가기';bar.append(a);document.querySelector('main')?.prepend(bar);}
 if(!/^\/wuwa-quests\/quests\/\d+\.html$/.test(path))return;
 if(point?.path?.split('#')[0]===path){requestAnimationFrame(()=>scrollTo(0,Number(point.y)||0));try{sessionStorage.removeItem('wuwa-reading-return');}catch{}}
 const actions=document.querySelector('.quest-actions');if(!actions)return;
 const toggle=document.createElement('button');toggle.type='button';toggle.textContent='용어 도움말 보기';toggle.setAttribute('aria-pressed','false');actions.append(toggle);
 let concepts,enabled=false,loading=false,dialog,origin;
 function close(){dialog?.close();origin?.focus({preventScroll:true});}
 function show(term,button){origin=button;if(!dialog){dialog=document.createElement('dialog');dialog.className='lore-context-dialog';dialog.setAttribute('aria-labelledby','context-title');document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog)close();});dialog.addEventListener('cancel',e=>{e.preventDefault();close();});}
  dialog.replaceChildren();const header=document.createElement('header'),h=document.createElement('h2'),exit=document.createElement('button');h.id='context-title';h.textContent=term.name;exit.type='button';exit.textContent='닫기';exit.addEventListener('click',close);header.append(h,exit);dialog.append(header);const p=document.createElement('p');p.textContent=term.summary;dialog.append(p);const label=document.createElement('small');label.textContent='근거 원문 · '+term.ref.label;dialog.append(label);const quote=document.createElement('blockquote');quote.textContent=term.ref.excerpt;dialog.append(quote);const links=document.createElement('div');links.className='lore-actions';const more=document.createElement('a');more.href=base+'/concepts/'+term.index+'.html';more.textContent='관련 설정과 원문 더 읽기 →';more.addEventListener('click',()=>{try{sessionStorage.setItem('wuwa-reading-return',JSON.stringify({path:location.pathname+location.hash,y:scrollY,title:document.querySelector('h1')?.textContent||'퀘스트'}));}catch{}});links.append(more);dialog.append(links);dialog.showModal();exit.focus();
 }
 function annotate(){const pattern=new RegExp(concepts.map(t=>t.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).sort((a,b)=>b.length-a.length).join('|'),'g');for(const speech of document.querySelectorAll('.quest-speech')){for(const text of [...speech.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE)){const raw=text.textContent;let last=0,matched=false;const frag=document.createDocumentFragment();for(const m of raw.matchAll(pattern)){matched=true;frag.append(document.createTextNode(raw.slice(last,m.index)));const term=concepts.find(t=>t.name===m[0]),button=document.createElement('button');button.type='button';button.className='quest-term';button.textContent=m[0];button.setAttribute('aria-label',m[0]+' 용어 도움말');button.addEventListener('click',()=>show(term,button));frag.append(button);last=m.index+m[0].length;}if(matched){frag.append(document.createTextNode(raw.slice(last)));text.replaceWith(frag);}}}}
 toggle.addEventListener('click',async()=>{if(loading)return;if(!enabled){try{loading=true;toggle.disabled=true;toggle.textContent='용어를 불러오는 중…';if(!concepts){const r=await fetch(base+'/settings/editorial.json');if(!r.ok)throw Error();const b=await r.json();concepts=b.concepts.map((t,index)=>({...t,index}));}annotate();enabled=true;toggle.textContent='용어 도움말 숨기기';toggle.setAttribute('aria-pressed','true');}catch{toggle.textContent='용어 도움말 다시 불러오기';}finally{loading=false;toggle.disabled=false;}}else{document.querySelectorAll('.quest-term').forEach(button=>button.replaceWith(document.createTextNode(button.textContent)));enabled=false;toggle.textContent='용어 도움말 보기';toggle.setAttribute('aria-pressed','false');}});
})();
