/* On-demand original texts. Shared Starlight navigation/theme surrounds this view. */
(()=>{'use strict';const root=document.getElementById('lore-reader'),base=root.dataset.base,assetVersion=new URL(document.currentScript.src).searchParams.get('v')||'',H=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let index,book,curated,relationRenderer,stripAssetMarkup,serial=0;const cache=new Map();
async function load(name){if(!cache.has(name)){const p=fetch(base+'/settings/'+name).then(r=>{if(!r.ok)throw Error('자료 파일을 읽지 못했습니다.');return r.json();}).catch(e=>{cache.delete(name);throw e;});cache.set(name,p);}return cache.get(name);}
const canonical=id=>index.aliases[id]||id,entry=id=>[...index.entries,...(index.diagnostic_entries||[])].find(e=>e.id===canonical(id));
const libraryReturn=value=>/^#\/library(?:\?[^#]*)?$/.test(value||'')?value:'#/library';
const sourceUrl=e=>{if(curated?.sources[e.id])return base+'/sources/'+curated.sources[e.id]+'.html?from='+encodeURIComponent(location.pathname+location.search+location.hash);const route=current(),from=route.parts[0]==='source'?libraryReturn(route.params.get('from')):libraryReturn(location.hash),url=base+e.page;return url+(url.includes('?')?'&':'?')+'from='+encodeURIComponent(from);};
const chapterLink=id=>{const c=book.chapters.find(c=>c.id===id);return c?`<a href="${base}/world/${id}.html"><strong>${H(c.title)}</strong><small>${H(c.question)}</small></a>`:'';};
const clean=s=>stripAssetMarkup(s).replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/?(?:te|color|size|b|i|u|ano|s)(?:[=\s][^>]*)?>/g,'').replace(/&(?:amp|lt|gt|quot|apos|#\d+|#x[0-9a-f]+);/gi,m=>{const known={'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'"};if(known[m.toLowerCase()])return known[m.toLowerCase()];const n=m.slice(0,3).toLowerCase()==='&#x'?parseInt(m.slice(3,-1),16):parseInt(m.slice(2,-1),10);return n>=0&&n<=0x10ffff?String.fromCodePoint(n):m;});
function text(raw){let out='',last=0;for(const m of raw.matchAll(/<te\s+href[=\s]+["']?(\d+)["']?\s*>(.*?)<\/te>/gs)){out+=H(clean(raw.slice(last,m.index)));const i=book.concepts.findIndex(c=>c.term_id===m[1]);out+=i>=0?`<a href="${base}/concepts/${i}.html">${H(clean(m[2]))}</a>`:H(clean(m[2]));last=m.index+m[0].length;}return out+H(clean(raw.slice(last)));}
const labels={type:'도감 종류',intensity:'도감 등급',heading_1:'기록 제목 1',description_1:'기록 1',heading_2:'기록 제목 2',description_2:'기록 2',info:'인물 소개',talent_name:'공명 능력',talent_document:'공명 기록',talent_certification:'안정성 기록',content:'본문',background:'배경',description:'설명',usage:'용도',obtained_description:'획득 설명',attributes_description:'제작·속성 설명',discovered_description:'발견 후 생태',undiscovered_description:'발견 전 설명',place:'서식 지역',region:'지역',sub_name:'設定 분류'.replace('設定','설정')};
function fields(row){const vals=row.values.filter(v=>(v.field==='type'&&row.category==='에코_도감')||!['name','title','type','birthday','sex','country','influence'].includes(v.field)),used=new Set();return vals.map(v=>{if(v.status==='OK'&&used.has(v.raw))return '';if(v.status==='OK')used.add(v.raw);const aliases=v.status==='OK'?vals.filter(a=>a!==v&&a.status==='OK'&&a.raw===v.raw):[];return `<section class="lore-field" id="field-${H(v.field)}"><div class="rw-reader not-content cva-page cva-reader-frame lore-field-reader" data-cva data-cva-profile="forma" data-reading-template="reader" data-reading-variant="original">${aliases.map(a=>`<span id="field-${H(a.field)}"></span>`).join('')}${window.CVA_COMPONENTS.heading({title:[v,...aliases].map(a=>labels[a.field]||a.field).join(' · '),level:2})}${v.status==='OK'?`<div class="lore-source-text">${text(v.raw)}</div>`:`<p class="lore-muted">${v.status==='EMPTY'?'원문이 비어 있습니다.':v.status==='NO_REFERENCE'?'원문 참조가 없습니다.':'한국어 원문 키를 찾지 못했습니다.'}</p>`}<details class="lore-provenance rw-disclosure not-content" data-reading-template="disclosure"><summary>원문·출처 확인</summary><dl>${[v,...aliases].map(a=>`<dt>원문 키</dt><dd>${H(a.text_id||'없음')}</dd><dt>언어 DB</dt><dd>${H(a.locale_db||'미확인')}</dd>`).join('')}<dt>상태</dt><dd>${H(v.status)}</dd></dl><pre>${H(v.raw)}</pre></details></div></section>`;}).join('');}
const current=()=>{const raw=location.hash.slice(1).replace(/^\//,'')||'library';const [path,q='']=raw.split('?');return {parts:path.split('/').map(decodeURIComponent),params:new URLSearchParams(q)};};
function row(e,q='',body=''){let excerpt=e.excerpt;if(q&&body){const at=body.toLocaleLowerCase('ko').indexOf(q.toLocaleLowerCase('ko'));if(at>=0){const from=Math.max(0,at-35);excerpt=(from?'…':'')+body.slice(from,at+100).replace(/\s+/g,' ')+(at+100<body.length?'…':'');}}return `<a class="lore-record" data-reading-link href="${H(sourceUrl(e))}">${window.CVA_COMPONENTS.panel({title:e.title,body:excerpt,label:e.category_label+(e.role_name?' · '+e.role_name:'')+(e.duplicate_count>1?' · 동일 원문 '+e.duplicate_count+'개':'')})}</a>`;}
async function render(){const token=++serial;root.innerHTML='<p role="status">자료를 불러오는 중입니다.</p>';try{
 if(!window.CVA_COMPONENTS)await import(base+'/cva/components.js');if(!relationRenderer)({sourceRelations:relationRenderer,stripOriginalAssetMarkup:stripAssetMarkup}=await import(base+'/lore/source-relations.js?v='+encodeURIComponent(assetVersion)));
 if(!index)[index,book,curated]=await Promise.all([load('index.json'),load('editorial.json'),load('curated-sources.json')]);const r=current(),q=(r.params.get('q')||'').trim(),technical=r.params.get('technical')==='1',diagnostics=r.params.get('diagnostics')==='1';let markup,title='원문 보관함',field='';
 if(r.parts[0]==='source'){
  const e=entry(r.parts.slice(1).join('/'));if(!e)throw Error('찾을 수 없는 원문입니다.');const rows=await load('records-'+e.chunk+'.json'),record=rows[e.id];title=e.title;field=r.params.get('field')||'';
  const adjacent=index.entries.filter(x=>x.id!==e.id&&x.group!=='technical'&&x.term_ids.filter(t=>e.term_ids.includes(t)).length>=2).slice(0,6);
  markup=`<a class="lore-more" href="${H(libraryReturn(r.params.get('from')))}">← 원문 보관함</a><p class="lore-kicker" style="margin-top:24px">${H(e.category_label)}</p>${e.role_id?`<a class="lore-more" href="${base}/people/${e.role_id}.html">${H(e.role_name)}의 자료 함께 읽기 ↗</a>`:''}${e.chapters.length?`<div class="lore-related">${e.chapters.map(chapterLink).join('')}</div>`:''}${fields(record)}${relationRenderer(e,{entry,url:sourceUrl,escape:H})}<details class="lore-provenance rw-disclosure not-content" data-reading-template="disclosure"><summary>원자료 기록 정보${e.duplicate_count>1?' · 동일 내용 '+e.duplicate_count+'개':''}</summary><dl><dt>자료 ID</dt><dd>${H(record.entry_id)}</dd><dt>테이블</dt><dd>${H(record.db+' / '+record.table)}</dd></dl><p>동일 종류·인물에서 모든 원문 읽기 필드가 같은 기록을 접어 표시합니다.</p><pre>${H(e.alias_ids.join('\n'))}</pre></details>${e.related_item?`<h2>문서가 연결한 아이템</h2>${row(entry(e.related_item))}`:''}${adjacent.length?`<h2>같은 용어로 더 읽기</h2><p class="lore-muted">둘 이상의 원문 용어 링크가 겹치는 자료를 탐색 후보로 모았습니다. 사건과 관계는 각 자료의 본문과 출처에서 확인할 수 있습니다.</p>${adjacent.map(e=>row(e)).join('')}`:''}`;
 }else{
  const group=r.params.get('group')||'',category=r.params.get('category')||'',role=r.params.get('role')||'',term=r.params.get('term')||'',body=r.params.get('body')==='1';
  let matches=[...index.entries,...(diagnostics?index.diagnostic_entries||[]:[])].filter(e=>(technical||e.group!=='technical')&&(!group||e.group===group)&&(!category||e.category===category)&&(!role||String(e.role_id)===role)&&(!term||e.term_ids.includes(term)));
  const texts={};if(body&&q){const chunks=[...new Set(matches.map(e=>e.chunk))];const bundles=await Promise.all(chunks.map(c=>load('records-'+c+'.json')));for(const records of bundles)for(const [id,e] of Object.entries(records))texts[id]=e.values.filter(v=>v.status==='OK').map(v=>v.text).join('\n');}
  const needle=q.toLocaleLowerCase('ko');matches=matches.filter(e=>!needle||[e.title,e.role_name,e.entry_id,body?texts[e.id]||'':''].join(' ').toLocaleLowerCase('ko').includes(needle));
  const total=Math.max(1,Math.ceil(matches.length/30)),page=Math.min(total,Math.max(1,Math.floor(Number(r.params.get('page')))||1)),start=(page-1)*30;
  const pager=n=>{const p=new URLSearchParams(r.params);p.set('page',n);return '#/library?'+p.toString();};
  markup=`<p class="lore-lead">해설에서 만난 자료를 더 읽어보세요. 인물·문서·지역·생태·장비와 튜토리얼·도움말 원문을 함께 보관합니다.</p><div class="lore-actions"><a href="${base}/world.html">세계관 해설</a><a href="${base}/people.html">인물별 설정</a><a href="#/library?group=documents">문서·편지·일기</a><a href="#/library?group=world">지역·생태·장비</a><a href="#/library?group=guides">튜토리얼·도움말</a></div><form class="lore-filter" id="lore-filter"><label>검색어<input type="search" name="q" value="${H(q)}" placeholder="예: 산화, 독무포자"></label><label>자료 종류<select name="category"><option value="">모든 종류</option>${index.categories.filter(c=>(technical||c.group!=='technical')&&(!group||c.group===group)).map(c=>`<option value="${H(c.id)}"${c.id===category?' selected':''}>${H(c.label)}</option>`).join('')}</select></label><label class="lore-check"><input type="checkbox" name="body" value="1"${body?' checked':''}>본문까지</label><label class="lore-check"><input type="checkbox" name="technical" value="1"${technical?' checked':''}>환경설정 UI 포함</label><label class="lore-check"><input type="checkbox" name="diagnostics" value="1"${diagnostics?' checked':''}>빈·테스트 원문 포함</label>${[['group',group],['role',role],['term',term]].filter(x=>x[1]).map(([k,v])=>`<input type="hidden" name="${k}" value="${H(v)}">`).join('')}<button type="submit">찾기</button></form>${role||term||group?'<a class="lore-more" href="#/library">현재 묶음 해제 · 전체 원문</a>':''}<p class="lore-count" role="status" aria-live="polite">${matches.length.toLocaleString('ko')}개 읽기 항목${matches.length?' · '+(start+1)+'–'+Math.min(start+30,matches.length):''}</p>${matches.length?matches.slice(start,start+30).map(e=>row(e,q,body?texts[e.id]:'')).join(''):'<div class="lore-empty"><h2>조건에 맞는 자료가 없습니다</h2><p>검색어를 짧게 바꾸거나 다른 자료 종류를 선택해 보세요.</p><a class="lore-more" href="#/library">전체 원문 보기</a></div>'}${total>1?`<nav class="lore-page" aria-label="원문 목록 페이지">${page>1?`<a href="${H(pager(page-1))}">← 이전</a>`:''}<span>${page} / ${total}</span>${page<total?`<a href="${H(pager(page+1))}">다음 →</a>`:''}</nav>`:''}<p class="lore-note">자료에는 미사용·테스트·미번역 항목이 포함될 수 있습니다. 수록만으로 출시 여부와 실제 플레이 가능 여부를 확정하지 않습니다.</p>`;
 }
 if(token!==serial)return;root.innerHTML='<div class="cva-page cva-reader-frame" data-cva data-cva-profile="forma">'+markup+'</div>';document.getElementById('_top').textContent=title;document.title=title+' · 명조 이야기 자료집';document.getElementById('lore-filter')?.addEventListener('submit',ev=>{ev.preventDefault();const p=new URLSearchParams(new FormData(ev.currentTarget));for(const [k,v] of [...p])if(!v)p.delete(k);location.hash='#/library?'+p.toString();});root.focus({preventScroll:true});if(field)document.getElementById('field-'+field)?.scrollIntoView();
 }catch(e){if(token!==serial)return;root.innerHTML=`<div class="lore-empty" role="alert"><h2>자료를 열지 못했습니다</h2><p>${H(e.message)}</p><button id="lore-retry" class="lore-more">다시 불러오기</button> <a class="lore-more" href="${base}/world.html">해설로 돌아가기</a></div>`;document.getElementById('lore-retry').addEventListener('click',render);}}
window.addEventListener('hashchange',render);render();})();
