import {readFile,writeFile,unlink} from 'node:fs/promises';
import crypto from 'node:crypto';
import path from 'node:path';
export async function generateAtlas({site,content,book,index,records,doc,H,refs,related}){
 const base='/wuwa-quests',atlas=JSON.parse(await readFile(path.join(site,'settings/atlas.json'),'utf8'));
 const all=[...atlas.regions,...atlas.sentinels,...atlas.cosmology];
 function validate(x){if(Array.isArray(x)){x.forEach(validate);return;}if(!x||typeof x!=='object')return;if(x.source_text_sha256&&x.id){const v=records[x.id]?.values.find(v=>v.field===x.field&&v.status==='OK');if(!v||crypto.createHash('sha256').update(v.raw).digest('hex')!==x.source_text_sha256)throw Error('Atlas evidence changed: '+x.id);if(x.excerpt&&!v.text.includes(x.excerpt))throw Error('Atlas excerpt mismatch: '+x.id);}Object.values(x).forEach(validate);}
 validate(atlas);
 for(const c of all)for(const q of c.dialogue||[]){const bytes=await readFile(path.join(site,'originals',q.quest_id+'.txt'));if(crypto.createHash('sha256').update(bytes).digest('hex')!==q.source_sha256||!bytes.toString('utf8').includes(q.quote))throw Error('Quest evidence changed: '+q.quest_id);const before=bytes.toString('utf8').slice(0,bytes.toString('utf8').indexOf(q.quote));if([...before.matchAll(/^장면 \d+:/gm)].length!==q.scene)throw Error('Quest scene mismatch');}
 await unlink(path.join(content,'world/evidence.md')).catch(e=>{if(e.code!=='ENOENT')throw e;});
 const url=s=>base+s;
 const intro=c=>`<div class="atlas-intro"><p class="lore-kicker">${H(c.question)}</p><p class="atlas-deck">${H(c.summary)}</p></div>`;
 const card=(c,group)=>`<a class="atlas-card" href="${url('/'+group+'/'+c.id+'.html')}"><span class="atlas-card-label">${group==='regions'?'지역':group==='sentinels'?'수호신':'세계의 원리'} <span aria-hidden="true">↗</span></span><h3>${H(c.title)}</h3><p>${H(c.question)}</p><small>${H(c.summary)}</small></a>`;
 const paragraphs=ps=>ps.map(p=>`<div class="atlas-reading ${p.kind==='reading'?'atlas-interpretation':''}"><span class="lore-kind">${p.kind==='reading'?'편집자의 해석':'원문 연결'}</span><p>${H(p.text)}</p>${refs(p.refs)}</div>`).join('');
 const relations=c=>c.edges.length?`<div class="atlas-relations" aria-label="${H(c.title)} 관계도">${c.edges.map((e,i)=>{const a=c.nodes.find(n=>n.name===e.a),b=c.nodes.find(n=>n.name===e.b);if(!a||!b)throw Error('Missing relation node');return `<article class="atlas-relation"><div class="atlas-edge"><a class="atlas-node" href="${url(a.url)}"><small>${H(a.kind)}</small><strong>${H(a.name)}</strong></a><div class="atlas-connector"><span>${H(e.verb)}</span><span class="atlas-arrow" aria-hidden="true">⟶</span></div><a class="atlas-node" href="${url(b.url)}"><small>${H(b.kind)}</small><strong>${H(b.name)}</strong></a></div><p class="atlas-relation-reason">${H(e.reason)}</p><details><summary>관계의 원문 근거</summary><span class="lore-kind">${e.kind==='reading'?'편집자의 해석':'원문 연결'}</span>${refs(e.refs)}</details></article>`;}).join('')}</div>`:'';
 const events=c=>c.timeline?`<h2 id="events">${H(c.timeline.title)}</h2><p class="atlas-caption">${H(c.timeline.note)}</p><ol class="atlas-timeline">${c.timeline.items.map((e,i)=>`<li><span class="atlas-event-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><h3>${H(e.title)}</h3><p>${H(e.text)}</p>${refs(e.refs)}</div></li>`).join('')}</ol>`:'';
 const comparisons=c=>c.comparison?`<h2 id="perspectives">같은 대상을 보는 서로 다른 기록</h2><div class="atlas-perspectives">${c.comparison.map(p=>`<article><h3>${H(p.title)}</h3><p>${H(p.text)}</p>${refs(p.refs)}</article>`).join('')}</div>`:'';
 function gather(x,out=[]){if(Array.isArray(x))x.forEach(v=>gather(v,out));else if(x&&typeof x==='object'){if(x.source_text_sha256&&x.id)out.push(x);else Object.values(x).forEach(v=>gather(v,out));}return [...new Map(out.map(r=>[r.id+'|'+r.field,r])).values()];}
 const evidence=c=>`<section class="atlas-evidence"><h2 id="evidence">이 페이지의 원문 근거</h2><p class="atlas-caption">아래 구절은 실제 텍스트의 발췌입니다. 자료 제목을 누르면 해당 본문 전체로 이동합니다. 전설·기록자의 추측은 그 성격을 본문에서 밝히고, 종합한 해석에는 별도 표시를 붙였습니다.</p>${gather(c).map(r=>`<details><summary>${H(r.label)} · ${H(r.field==='content'?'본문':r.field==='discovered_description'?'발견 후 생태':r.field==='background'?'배경':r.field==='info'?'소개':r.field==='talent_document'?'공명 기록':'안정성 기록')}</summary><blockquote>${H(r.excerpt)}</blockquote>${refs([r])}</details>`).join('')}${(c.dialogue||[]).map(q=>`<details><summary>퀘스트 · ${H(q.title)} · 장면 ${q.scene} · ${H(q.speaker)}</summary><blockquote>${H(q.quote)}</blockquote><a href="${url('/quests/'+q.quest_id+'.html#scene-'+q.scene)}">해당 대사 장면 전체 읽기 ↗</a></details>`).join('')}</section>`;
 const people=ids=>`<div class="atlas-people">${ids.map(id=>index.characters.find(p=>p.id===id)).filter(Boolean).map(p=>`<a href="${url('/people/'+p.id+'.html')}"><strong>${H(p.name)}</strong><small>${H(p.influence)}</small></a>`).join('')}</div>`;
 const concepts=ids=>`<div class="lore-pills">${ids.map(i=>`<a href="${url('/concepts/'+i+'.html')}">${H(book.concepts[i].name)}</a>`).join('')}</div>`;
 await doc('world','세계관 설정집',`<div class="atlas-home-intro"><p class="lore-kicker">한 기록에서, 더 넓은 세계로</p><p class="atlas-deck">낯선 개념을 이해하고,<br>인물의 선택과 도시의 기억을 이어 읽습니다.</p></div><div class="atlas-axis-grid"><a href="${url('/regions.html')}"><span>01 · 지역</span><h2>이곳은 왜<br>이런 모습일까?</h2><p>도시의 역사 · 신앙 · 생활 · 주요 사건</p><strong>지역에서 시작하기 →</strong></a><a href="${url('/people.html')}"><span>02 · 인물</span><h2>이 사람은 왜<br>이렇게 선택했을까?</h2><p>과거 · 관계 · 소속 · 발언 · 전환점</p><strong>인물에서 시작하기 →</strong></a><a href="${url('/cosmology.html')}"><span>03 · 세계의 큰 설정</span><h2>이 세계는<br>어떻게 움직일까?</h2><p>재앙 · 주파수 · 힘 · 문명과 질서</p><strong>세계의 원리부터 읽기 →</strong></a></div><div class="atlas-home-links"><a href="${url('/sentinels.html')}"><strong>수호신과 문명</strong><span>용의 별자리 · 임페라토르 · 여우의 별자리</span></a><a href="${url('/relationships.html')}"><strong>관계 따라 읽기</strong><span>누가 누구를 보호하고, 무엇을 바꾸었는가</span></a><a href="${url('/events.html')}"><strong>전환점 따라 읽기</strong><span>시간을 계승한 금희 · 빛을 남긴 엑소스트라이더</span></a></div><h2>먼저 함께 읽어볼 기록</h2><div class="atlas-card-grid">${atlas.regions.map(c=>card(c,'regions')).join('')}</div><div class="lore-actions"><a href="${url('/library.html')}">원문 보관함</a><a href="${url('/settings/world-guide.md')}" download>설정집 문서 내려받기 ↓</a></div><p class="atlas-caption">사건의 결말과 인물의 과거가 포함됩니다. 원문 연결과 편집자의 해석을 구분하며, 각 설명 아래에서 근거를 확인할 수 있습니다.</p>`,'지역·인물·세계의 큰 설정을 관계와 사건, 원문으로 이어 읽는 명조 설정집',false);
 for(const [group,title,lead,cs] of [['regions','지역별 설정','도시의 현재에서 출발해, 그 모습을 만든 보호·제도·사건을 읽습니다.',atlas.regions],['cosmology','세계관의 큰 설정','개념의 정의를 먼저 이해하고, 지역과 인물에 드러나는 구체적인 사례로 확장합니다.',atlas.cosmology],['sentinels','수호신과 문명','무엇을 지키고, 어떤 힘으로 문명을 이끄는가. 수호신의 권능과 그 힘을 이어받거나 해석하는 사람들을 함께 읽습니다.',atlas.sentinels]]){
  await doc(group,title,`<p class="atlas-deck">${lead}</p><div class="atlas-card-grid">${cs.map(c=>card(c,group)).join('')}</div>${group==='sentinels'?'<p class="lore-note">파수인은 검은 해안의 인물이며, 엑소스트라이더는 메카스카우트로 기록됩니다. 이 목록은 원문이 수호신으로 명시한 존재를 중심으로 구성했습니다.</p>':''}`,lead,false);
  for(const c of cs){let body=`<nav class="atlas-breadcrumb" aria-label="설정 위치"><a href="${url('/world.html')}">설정집</a><span aria-hidden="true">›</span><a href="${url('/'+group+'.html')}">${title}</a>${c.parent?`<span aria-hidden="true">›</span><span>리나시타의 도시 국가</span>`:''}</nav>${intro(c)}<nav class="atlas-jump" aria-label="이 설정에서 읽기"><a href="#context">맥락</a>${c.edges.length?'<a href="#relations">관계</a>':''}${c.timeline?'<a href="#events">사건</a>':''}${c.comparison?'<a href="#perspectives">기록 비교</a>':''}<a href="#next">이어 읽기</a></nav><h2 id="context">이 기록들을 함께 읽는 이유</h2>${paragraphs(c.paragraphs)}${c.edges.length?'<h2 id="relations">관계로 이해하기</h2><p class="atlas-caption">연결 이름이 관계의 성격을 나타냅니다. 관계 아래의 설명에서 연결 이유를 읽고 원문 근거를 확인할 수 있습니다.</p>'+relations(c):''}${events(c)}${comparisons(c)}`;
   if(c.dialogue?.length)body+=`<h2>선택의 이유를 대사에서 읽기</h2><div class="atlas-perspectives">${c.dialogue.map(q=>`<article><h3>${H(q.label)}</h3><span class="lore-kind">${H(q.speaker)}의 발언</span><blockquote>${H(q.quote)}</blockquote><a href="${url('/quests/'+q.quest_id+'.html#scene-'+q.scene)}">${H(q.title)} · 장면 ${q.scene} ↗</a></article>`).join('')}</div>`;
   if(c.applications)body+=`<h2>이 원리가 지역에 드러나는 모습</h2><div class="atlas-card-grid">${c.applications.map(id=>card(atlas.regions.find(r=>r.id===id),'regions')).join('')}</div>`;
   if(c.bridge)body+=`<aside class="atlas-bridge"><h2>${H(c.bridge.title)}</h2><p>${H(c.bridge.text)}</p>${refs(c.bridge.refs)}<a href="${url(c.bridge.url)}">이 질문에서 이어 읽기 →</a></aside>`;
   body+=`<h2 id="next">지금의 질문에서 더 깊이 읽기</h2>${c.region?`<div class="lore-actions"><a href="${url('/regions/'+c.region+'.html')}">이 수호신이 이끄는 지역 →</a></div>`:''}${people(c.roles)}${concepts(c.concepts)}${related(c.chapters)}${evidence(c)}`;
   await doc(group+'/'+c.id,c.title,body,c.question);
  }
 }
 await doc('relationships','관계 따라 읽기',`<p class="atlas-deck">같은 단어보다, 서로에게 하는 일을 따라갑니다.</p><nav class="atlas-jump" aria-label="지역 관계 바로가기">${atlas.regions.map(c=>`<a href="#relation-${c.id}">${H(c.title.split(' · ')[0])}</a>`).join('')}</nav>${atlas.regions.map(c=>`<h2 id="relation-${c.id}">${H(c.title)}</h2><p>${H(c.question)}</p>${relations(c)}<a class="lore-more" href="${url('/regions/'+c.id+'.html#evidence')}">지역 맥락과 하단 원문 근거 →</a>`).join('')}${evidence(atlas.regions.map(c=>c.edges))}`,'관계 이름과 원문 근거를 함께 읽는 지역별 관계도');
 await doc('events','전환점 따라 읽기',`<p class="atlas-deck">인물의 결정과 문명의 변화가 맞물리는 순간을 읽습니다.</p><p class="atlas-caption">지역별 기록에 명시된 사건의 전후 관계를 따라 배열했습니다.</p>${atlas.regions.filter(c=>c.timeline).map(c=>`<h2>${H(c.title)}</h2>${events(c).replace('id="events"','id="events-'+c.id+'"')}<a class="lore-more" href="${url('/regions/'+c.id+'.html')}">관계와 배경을 함께 읽기 →</a>`).join('')}${evidence(atlas.regions.filter(c=>c.timeline).map(c=>c.timeline))}`,'원문이 확인하는 사건 흐름과 전환점');
 function regionFor(p){return atlas.regions.find(r=>r.roles.includes(p.id))?.id||(p.influence.includes('금주')?'jinzhou':p.influence.includes('검은 해안')||p.influence.includes('검은해안')?'black-shores':/라군나|몬텔리|피살리아|수도회|우인/.test(p.influence)?'rinascita':p.influence.includes('일곱 언덕')?'seven-hills':/스타토치|라하이|로야|스페이스 트렉/.test(p.influence)?'raha':p.influence.includes('몽주')?'mongju':'other');}
 await doc('people','인물별 설정',`<p class="atlas-deck">한 사람의 소개에서 시작해, 소속과 관계, 과거와 선택을 함께 읽습니다.</p><div class="lore-people-controls atlas-person-controls" role="search"><label for="lore-person-q">인물 찾기<input id="lore-person-q" type="search" placeholder="예: 금희, 파수인" autocomplete="off"></label><label for="lore-person-region">활동 지역·소속<select id="lore-person-region"><option value="">모든 지역</option>${atlas.regions.map(r=>`<option value="${r.id}">${H(r.title.split(' · ')[0])}</option>`).join('')}<option value="other">그 밖의 소속·미확인</option></select></label><p id="lore-person-count" role="status" aria-live="polite">${index.characters.length}개 인물 묶음</p></div>${[...atlas.regions.map(r=>[r.id,r.title.split(' · ')[0]]),['other','그 밖의 소속·미확인']].map(([id,label])=>`<section class="atlas-person-group" data-region="${id}"><h2>${H(label)}</h2><div class="lore-person-grid">${index.characters.filter(p=>regionFor(p)===id).map(p=>`<a class="lore-person-card" data-name="${H(p.name)}" data-region="${id}" href="${url('/people/'+p.id+'.html')}"><h3>${H(p.name)}</h3><p>${H(p.influence)}</p><small>출신: ${H(p.country||'미확인')}<br>이야기 ${p.counts.stories||0} · 소장품 ${p.counts.goods||0}</small></a>`).join('')}</div></section>`).join('')}<p id="lore-person-empty" hidden>찾는 인물이 없습니다. 이름이나 지역 조건을 바꿔보세요.</p><p class="atlas-caption">활동 지역과 소속을 기준으로 묶고, 출신은 별도로 표시합니다. 미사용·테스트 자료가 포함될 수 있으며 실제 출시 여부를 확정하지 않습니다.</p><script src="${base}/lore/people.js" defer></script>`,'소속·지역과 관계를 따라 찾아 읽는 인물 자료',false,false);

 for(const [i,c] of book.concepts.entries()){
  const file=path.join(content,'concepts/'+i+'.md'),raw=await readFile(file,'utf8');
  const connected=[...atlas.regions.map(c=>({c,group:'regions'})),...atlas.cosmology.map(c=>({c,group:'cosmology'}))].filter(x=>x.c.concepts.includes(i));
  const row=records[index.aliases[c.ref.id]||c.ref.id],v=row.values.find(v=>v.field===c.ref.field),exact={...c.ref,excerpt:v.text.slice(0,240)};
  await writeFile(file,raw+`<h2>이 개념이 삶과 지역에 드러나는 모습</h2><div class="atlas-card-grid">${connected.map(x=>card(x.c,x.group)).join('')}</div>${evidence({refs:[exact]})}`);
 }
 // Insert semantic context above the existing complete profile/stories, without changing their primary text.
 for(const p of index.characters){const rid=regionFor(p),region=atlas.regions.find(r=>r.id===rid),file=path.join(content,'people/'+p.id+'.md'),raw=await readFile(file,'utf8'),end=raw.indexOf('\n---',4)+4,edges=region?.edges.filter(e=>e.a===p.name||e.b===p.name)||[];const lead=region?`\n\n<div class="atlas-person-context"><span class="lore-kicker">${H(region.title.split(' · ')[0])}에서 함께 읽기</span><a href="${url('/regions/'+rid+'.html')}">${H(region.question)} →</a>${edges.length?relations({...region,edges}):''}${p.id==='1304'?`<a class="lore-more" href="${url('/regions/jinzhou.html#events')}">금희가 시간 제어를 이어받기까지 →</a>`:''}</div>`:'';const sources=index.entries.filter(e=>String(e.role_id)===p.id&&['profile','stories','goods'].includes(e.chunk));const bottom=`<section class="atlas-evidence"><h2>이 페이지의 원문 자료</h2><p class="atlas-caption">위에 수록한 소개·기록·이야기·소장품의 원문입니다. 자료별 본문과 출처를 확인할 수 있습니다.</p><div class="lore-source-list">${sources.map(e=>`<a href="${url(e.page)}"><small>${H(e.category_label)}</small><strong>${H(e.title)}</strong></a>`).join('')}</div></section>`;await writeFile(file,raw.slice(0,end)+lead+raw.slice(end)+'\n'+bottom);}
 let guide='# 명조 세계관 설정집\n\n지역·인물·세계의 큰 설정을 관계와 사건, 원문으로 이어 읽습니다.\n\n';
 for(const [name,group,cs] of [['지역','regions',atlas.regions],['수호신','sentinels',atlas.sentinels],['세계관의 큰 설정','cosmology',atlas.cosmology]]){guide+='## '+name+'\n\n';for(const c of cs){guide+='### '+c.title+'\n\n**질문:** '+c.question+'\n\n'+c.summary+'\n\n';for(const p of c.paragraphs)guide+=(p.kind==='reading'?'**편집자의 해석** ':'**원문 연결** ')+p.text+'\n\n'+p.refs.map(r=>'['+r.label+'](https://mizan0515.github.io'+base+index.entries.find(e=>e.id===r.id).page+'#field-'+r.field+')').join(' · ')+'\n\n';for(const e of c.edges)guide+='- '+e.a+' → **'+e.verb+'** → '+e.b+': '+e.reason+'\n';if(c.timeline){guide+='\n**'+c.timeline.title+'**\n\n';c.timeline.items.forEach((e,i)=>{guide+=(i+1)+'. **'+e.title+'** — '+e.text+'\n';});}guide+='\n[화면에서 관계·원문 함께 읽기](https://mizan0515.github.io'+base+'/'+group+'/'+c.id+'.html)\n\n';}}
 await writeFile(path.join(site,'settings/world-guide.md'),guide);
 console.log(JSON.stringify({atlasEvidence:'PASS',regions:atlas.regions.length,sentinels:atlas.sentinels.length,conceptClusters:atlas.cosmology.length,relations:atlas.regions.reduce((n,c)=>n+c.edges.length,0)}));
}
