import {createReadingSections} from './reading-sections.mjs';
import {buildReadingData} from './reading-data.mjs';
import {createReadingKit} from '../src/lib/reading-kit/render.mjs';
import {readFile,writeFile,unlink} from 'node:fs/promises';
import crypto from 'node:crypto';
import path from 'node:path';
export async function generateAtlas({site,content,book,index,records,doc,H,refs,related}){
 const base='/wuwa-quests',atlas=JSON.parse(await readFile(path.join(site,'settings/atlas.json'),'utf8'));
 const all=[...atlas.regions,...atlas.sentinels,...atlas.cosmology,...atlas.factions];
 const groupFor=c=>atlas.regions.includes(c)?"regions":atlas.sentinels.includes(c)?"sentinels":atlas.factions.includes(c)?"factions":"cosmology";
 function validate(x){if(Array.isArray(x)){x.forEach(validate);return;}if(!x||typeof x!=='object')return;if(x.source_text_sha256&&x.id){const v=records[x.id]?.values.find(v=>v.field===x.field&&v.status==='OK');if(!v||crypto.createHash('sha256').update(v.raw).digest('hex')!==x.source_text_sha256)throw Error('Atlas evidence changed: '+x.id);if(x.excerpt&&!v.text.includes(x.excerpt))throw Error('Atlas excerpt mismatch: '+x.id);}Object.values(x).forEach(validate);}
 validate(atlas);
 for(const c of all)for(const q of c.dialogue||[]){const bytes=await readFile(path.join(site,'originals',q.quest_id+'.txt'));if(crypto.createHash('sha256').update(bytes).digest('hex')!==q.source_sha256||!bytes.toString('utf8').includes(q.quote))throw Error('Quest evidence changed: '+q.quest_id);const before=bytes.toString('utf8').slice(0,bytes.toString('utf8').indexOf(q.quote));if([...before.matchAll(/^장면 \d+:/gm)].length!==q.scene)throw Error('Quest scene mismatch');}
 await unlink(path.join(content,'world/evidence.md')).catch(e=>{if(e.code!=='ENOENT')throw e;});
 const url=s=>base+s;
 const entityLinks=new Map(index.characters.map(p=>[p.name,'/people/'+p.id+'.html']));
 for(const c of all) entityLinks.set(c.title.split(' · ')[0],'/'+groupFor(c)+'/'+c.id+'.html');
 for(const [i,c] of book.concepts.entries()) if(!entityLinks.has(c.name))entityLinks.set(c.name,'/concepts/'+i+'.html');
 const entitySources=new Map();
 for(const c of all)for(const n of c.nodes){
  if(entityLinks.has(n.name)){n.url=entityLinks.get(n.name);continue;}
  const sources=gather(c).filter(r=>r.excerpt.includes(n.name)||r.label.includes(n.name));
  if(!sources.length)continue;
  const slug=crypto.createHash('sha256').update(n.name).digest('hex').slice(0,16);
  n.url='/entities/'+slug+'.html';entityLinks.set(n.name,n.url);entitySources.set(n.name,{slug,sources});
 }
 const namePattern=new RegExp([...entityLinks.keys()].filter(n=>n.length>1).sort((a,b)=>b.length-a.length).map(n=>n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'g');
 function text(s){s=String(s);let out='',last=0;const seen=new Set();for(const m of s.matchAll(namePattern)){out+=H(s.slice(last,m.index));const name=m[0];if(name==='구원'||seen.has(name)||seen.size>=3)out+=H(name);else{out+=`<a class="setting-entity-link" href="${url(entityLinks.get(name))}">${H(name)}</a>`;seen.add(name);}last=m.index+name.length;}return out+H(s.slice(last));}
 for(const [name,{slug,sources}] of entitySources)await doc('entities/'+slug,name,`<p class="atlas-deck">${H(name)}에 관한 기록</p><div class="setting-sections">${sources.map(r=>`<section><h2>${H(r.label)}</h2><div class="lore-source-text">${H(r.excerpt)}</div>${refs([r])}</section>`).join('')}</div>`,name+'의 원문 기록');
 for(const c of all)for(const n of c.nodes)if(!entityLinks.has(n.name))entityLinks.set(n.name,n.url);
 for(const c of all)for(const n of c.topology?.nodes||[])if(entityLinks.has(n.name))n.url=url(entityLinks.get(n.name));
 all.forEach(c=>refs(gather(c)));
 const normalized=await buildReadingData({source:path.join(site,'source'),index,records,atlas,entityLinks});
 const model=c=>normalized.cluster(normalized.data.clusters.find(x=>x.id.endsWith('/'+c.id)).id);
 const claimMap=new Map(normalized.data.claims.map(c=>[c.id,c])),evidenceMap=new Map(normalized.data.evidence.map(e=>[e.id,e]));
 const claim=id=>{const c=claimMap.get(id);return {...c,evidence:c.evidenceIds.map(id=>evidenceMap.get(id))};};
 const kit=createReadingKit({inline:text,evidence:rs=>rs.map(r=>`<blockquote>${H(r.quote)}</blockquote><a href="${H(r.url)}">${H(r.title)} ↗</a>`).join('')});
 const sections=createReadingSections({H,text,refs,kit,model,claim,evidenceMap});
 const intro=c=>`<div class="atlas-intro"><p class="lore-kicker">${H(c.question)}</p><p class="atlas-deck">${text(c.summary)}</p></div>`;
 const card=(c,group)=>`<a class="atlas-card" href="${url('/'+group+'/'+c.id+'.html')}"><span class="atlas-card-label">${group==='regions'?'지역':group==='sentinels'?'수호신':group==='factions'?'세력·인물':'세계의 원리'} <span aria-hidden="true">↗</span></span><h3>${H(c.title)}</h3><p>${H(c.question)}</p><small>${H(c.summary)}</small></a>`;
 const paragraphs=ps=>ps.map(p=>`<div class="atlas-reading ${p.kind==='reading'?'atlas-interpretation':''}"><span class="lore-kind">${p.kind==='reading'?'편집자의 해석':'원문 연결'}</span><p>${text(p.text)}</p>${refs(p.refs)}</div>`).join('');
 const relations=c=>kit.network(model(c).relations.filter(r=>c.edges.some(e=>e.a===r.from.name&&e.b===r.to.name)),{id:'relations-'+c.id,title:c.title+'의 관계',focusId:model(c).entityId});
 const events=c=>c.timeline?`<h2 id="events">${H(c.timeline.title)}</h2>`+kit.timeline(model(c).events,{ordered:model(c).timeOrdered,note:model(c).timeNote}):'';
 const comparisons=c=>c.comparison?'<h2 id="perspectives">같은 대상을 보는 서로 다른 기록</h2>'+kit.comparison(model(c).comparisons.map(p=>({...p,...claim(p.claimId)}))):'';
 function gather(x,out=[]){if(Array.isArray(x))x.forEach(v=>gather(v,out));else if(x&&typeof x==='object'){if(x.source_text_sha256&&x.id)out.push(x);else Object.values(x).forEach(v=>gather(v,out));}return [...new Map(out.map(r=>[r.id+'|'+r.field,r])).values()];}
 const evidence=c=>`<section class="atlas-evidence"><h2 id="evidence">이 페이지의 원문 근거</h2><p class="atlas-caption">아래 구절은 실제 텍스트의 발췌입니다. 자료 제목을 누르면 해당 본문 전체로 이동합니다. 전설·기록자의 추측은 그 성격을 본문에서 밝히고, 종합한 해석에는 별도 표시를 붙였습니다.</p>${gather(c).map(r=>`<details><summary>${H(r.label)} · ${H(r.field==='content'?'본문':r.field==='discovered_description'?'발견 후 생태':r.field==='undiscovered_description'?'발견 전 소개':r.field==='background'?'배경':r.field==='info'?'소개':r.field==='talent_document'?'공명 기록':'안정성 기록')}</summary><blockquote>${H(r.excerpt)}</blockquote>${refs([r])}</details>`).join('')}${(c.dialogue||[]).map(q=>`<details><summary>퀘스트 · ${H(q.title)} · 장면 ${q.scene} · ${H(q.speaker)}</summary><blockquote>${H(q.quote)}</blockquote><a href="${url('/quests/'+q.quest_id+'.html#scene-'+q.scene)}">해당 대사 장면 전체 읽기 ↗</a></details>`).join('')}</section>`;
 const people=ids=>`<div class="atlas-people">${ids.map(id=>index.characters.find(p=>p.id===id)).filter(Boolean).map(p=>`<a href="${url('/people/'+p.id+'.html')}"><strong>${H(p.name)}</strong><small>${H(p.influence)}</small></a>`).join('')}</div>`;
 const concepts=ids=>`<div class="lore-pills">${ids.map(i=>`<a href="${url('/concepts/'+i+'.html')}">${H(book.concepts[i].name)}</a>`).join('')}</div>`;
 const directory=(title,lead,cs,group)=>`<section><h2>${H(title)}</h2><p>${H(lead)}</p><div class="world-directory-links">${cs.map(c=>`<a href="${url('/'+group+'/'+c.id+'.html')}"><strong>${H(c.title)}</strong><span>${H(c.summary)}</span></a>`).join('')}</div></section>`;
 await doc('world','설정집',`<p class="atlas-deck">솔라리스의 재앙과 힘, 지역의 생활과 역사, 인물의 기록을 함께 읽습니다.</p><nav class="atlas-jump" aria-label="설정집 탐색"><a href="#world-principles">세계의 원리</a><a href="#world-regions">지역</a><a href="#world-factions">세력과 위협</a><a href="${url('/people.html')}">인물</a><a href="${url('/library.html')}">원문 보관함</a></nav><div class="world-directory"><div id="world-factions">${directory("세력과 위협","조직의 구성과 목적, 적대적인 인물의 발언, 주인공이 마주치는 장면을 함께 읽습니다.",atlas.factions,"factions")}</div><div id="world-principles">${directory('세계관의 큰 설정','세계의 변화 → 재앙과 생태 → 공명과 기술. 각 개념의 정의와 지역에 드러난 사례를 읽습니다.',atlas.cosmology,'cosmology')}</div><div id="world-regions">${directory('지역의 역사와 생활','지역의 개요와 주요 장소에서 시작해 제도·신앙·생활·사건으로 이어집니다.',atlas.regions,'regions')}</div>${directory('수호신과 문명','수호신의 기록과 권능, 지역과 인물에게 이어지는 관계를 읽습니다.',atlas.sentinels,'sentinels')}</div><div class="lore-actions"><a href="${url('/people.html')}">인물별 설정</a><a href="${url('/relationships.html')}">관계 따라 읽기</a><a href="${url('/events.html')}">사건과 전환점</a></div>`,'명조의 세계관·지역·인물과 원문 기록',false);
 for(const [group,title,lead,cs] of [['factions','세력과 위협','조직의 구성과 행동, 간부의 발언과 주인공이 마주치는 장면을 함께 읽습니다.',atlas.factions],['regions','지역별 설정','도시의 현재에서 출발해, 그 모습을 만든 보호·제도·사건을 읽습니다.',atlas.regions],['cosmology','세계관의 큰 설정','개념의 정의를 먼저 이해하고, 지역과 인물에 드러나는 구체적인 사례로 확장합니다.',atlas.cosmology],['sentinels','수호신과 문명','무엇을 지키고, 어떤 힘으로 문명을 이끄는가. 수호신의 권능과 그 힘을 이어받거나 해석하는 사람들을 함께 읽습니다.',atlas.sentinels]]){
  await doc(group,title,`<p class="atlas-deck">${lead}</p><div class="atlas-card-grid">${cs.map(c=>card(c,group)).join('')}</div>${group==='sentinels'?'<p class="lore-note">파수인은 검은 해안의 인물이며, 엑소스트라이더는 메카스카우트로 기록됩니다. 이 목록은 원문이 수호신으로 명시한 존재를 중심으로 구성했습니다.</p>':''}`,lead,false);
  for(const c of cs){let body=`<nav class="atlas-breadcrumb" aria-label="설정 위치"><a href="${url('/world.html')}">설정집</a><span aria-hidden="true">›</span><a href="${url('/'+group+'.html')}">${title}</a>${c.parent?`<span aria-hidden="true">›</span><span>리나시타의 도시 국가</span>`:''}</nav>${intro(c)}<span id="overview-0"></span><nav class="atlas-jump" aria-label="이 설정에서 읽기"><a href="#overview-0">개요</a>${c.topology||c.edges.length?`<a href="#${H(c.topology?.id||'structure')}">핵심 구조</a>`:''}${(c.sections||[]).map((s,i)=>`<a href="#section-${i}">${H(s.title)}</a>`).join('')}${c.edges.length?'<a href="#relations">관계</a>':''}${c.timeline?'<a href="#events">사건</a>':''}${c.comparison?'<a href="#perspectives">기록 비교</a>':''}<a href="#next">이어 읽기</a></nav>${c.edges.length?'<span id="relations"></span>':''}${model(c).topology?kit.topology(model(c).topology):kit.network(model(c).relations,{id:'structure',title:'関係 한눈에'.replace('関係','관계'),focusId:model(c).entityId})}${model(c).containment?`<section id="containment"><h2>${H(model(c).containment.title)}</h2>${kit.containment({...model(c).containment,evidence:model(c).containment.evidenceIds.map(id=>evidenceMap.get(id))})}</section>`:''}${sections(c)}${events(c)}${comparisons(c)}`;
   if(c.applications)body+=`<h2>이 원리가 지역에 드러나는 모습</h2><div class="atlas-card-grid">${c.applications.map(id=>card(atlas.regions.find(r=>r.id===id),'regions')).join('')}</div>`;
   if(c.bridge)body+=`<aside class="atlas-bridge"><h2>${H(c.bridge.title)}</h2><p>${H(c.bridge.text)}</p>${refs(c.bridge.refs)}<a href="${url(c.bridge.url)}">이 질문에서 이어 읽기 →</a></aside>`;
   body+=`<h2 id="next">지금의 질문에서 더 깊이 읽기</h2>${c.region?`<div class="lore-actions"><a href="${url('/regions/'+c.region+'.html')}">이 수호신이 이끄는 지역 →</a></div>`:''}${people(c.roles)}${concepts(c.concepts)}${related(c.chapters)}${evidence(c)}`;
   await doc(group+'/'+c.id,c.title,body,c.question,false);
  }
 }
 await doc('relationships','관계 따라 읽기',`<p class="atlas-deck">같은 단어보다, 서로에게 하는 일을 따라갑니다.</p><nav class="atlas-jump" aria-label="지역 관계 바로가기">${[...atlas.factions,...atlas.regions].map(c=>`<a href="#relation-${c.id}">${H(c.title.split(' · ')[0])}</a>`).join('')}</nav>${[...atlas.factions,...atlas.regions].map(c=>`<h2 id="relation-${c.id}">${H(c.title)}</h2><p>${H(c.question)}</p>${relations(c)}<a class="lore-more" href="${url('/'+groupFor(c)+'/'+c.id+'.html#evidence')}">본문과 원문 근거 →</a>`).join('')}${evidence([...atlas.factions,...atlas.regions].map(c=>c.edges))}`,'관계 이름과 원문 근거를 함께 읽는 세력·지역의 관계도');
 await doc('events','전환점 따라 읽기',`<p class="atlas-deck">인물의 결정과 문명의 변화가 맞물리는 순간을 읽습니다.</p><p class="atlas-caption">지역별 기록에 명시된 사건의 전후 관계를 따라 배열했습니다.</p>${atlas.regions.filter(c=>c.timeline).map(c=>`<h2>${H(c.title)}</h2>${events(c).replace('id="events"','id="events-'+c.id+'"')}<a class="lore-more" href="${url('/regions/'+c.id+'.html')}">관계와 배경을 함께 읽기 →</a>`).join('')}${evidence(atlas.regions.filter(c=>c.timeline).map(c=>c.timeline))}`,'원문이 확인하는 사건 흐름과 전환점');
 function regionFor(p){return atlas.regions.find(r=>r.roles.includes(p.id))?.id||(p.influence.includes('금주')?'jinzhou':p.influence.includes('검은 해안')||p.influence.includes('검은해안')?'black-shores':/라군나|몬텔리|피살리아|수도회|우인/.test(p.influence)?'rinascita':p.influence.includes('일곱 언덕')?'seven-hills':/스타토치|라하이|로야|스페이스 트렉/.test(p.influence)?'raha':p.influence.includes('몽주')?'mongju':'other');}
 await doc('people','인물별 설정',`<p class="atlas-deck">한 사람의 소개에서 시작해, 소속과 관계, 과거와 선택을 함께 읽습니다.</p><div class="lore-people-controls atlas-person-controls" role="search"><label for="lore-person-q">인물 찾기<input id="lore-person-q" type="search" placeholder="예: 금희, 파수인" autocomplete="off"></label><label for="lore-person-region">활동 지역·소속<select id="lore-person-region"><option value="">모든 지역</option>${atlas.regions.map(r=>`<option value="${r.id}">${H(r.title.split(' · ')[0])}</option>`).join('')}<option value="other">그 밖의 소속·미확인</option></select></label><p id="lore-person-count" role="status" aria-live="polite">${index.characters.length}개 인물 묶음</p></div>${[...atlas.regions.map(r=>[r.id,r.title.split(' · ')[0]]),['other','그 밖의 소속·미확인']].map(([id,label])=>`<section class="atlas-person-group" data-region="${id}"><h2>${H(label)}</h2><div class="lore-person-grid">${index.characters.filter(p=>regionFor(p)===id).map(p=>`<a class="lore-person-card" data-name="${H(p.name)}" data-region="${id}" href="${url('/people/'+p.id+'.html')}"><h3>${H(p.name)}</h3><p>${H(p.influence)}</p><small>출신: ${H(p.country||'미확인')}<br>이야기 ${p.counts.stories||0} · 소장품 ${p.counts.goods||0}</small></a>`).join('')}</div></section>`).join('')}<p id="lore-person-empty" hidden>찾는 인물이 없습니다. 이름이나 지역 조건을 바꿔보세요.</p><p class="atlas-caption">활동 지역과 소속을 기준으로 묶고, 출신은 별도로 표시합니다. 미사용·테스트 자료가 포함될 수 있으며 실제 출시 여부를 확정하지 않습니다.</p><script src="${base}/lore/people.js" defer></script>`,'소속·지역과 관계를 따라 찾아 읽는 인물 자료',false,false);

 for(const [i,c] of book.concepts.entries()){
  const file=path.join(content,'concepts/'+i+'.md'),raw=await readFile(file,'utf8');
  const connected=[...atlas.regions.map(c=>({c,group:'regions'})),...atlas.cosmology.map(c=>({c,group:'cosmology'})),...atlas.factions.map(c=>({c,group:'factions'}))].filter(x=>x.c.concepts.includes(i));
  const row=records[index.aliases[c.ref.id]||c.ref.id],v=row.values.find(v=>v.field===c.ref.field),exact={...c.ref,excerpt:v.text.slice(0,240)};
  await writeFile(file,raw+`<h2>이 개념이 삶과 지역에 드러나는 모습</h2><div class="atlas-card-grid">${connected.map(x=>card(x.c,x.group)).join('')}</div>${evidence({refs:[exact]})}`);
 }
 // Insert semantic context above the existing complete profile/stories, without changing their primary text.
 for(const p of index.characters){const rid=regionFor(p),region=atlas.regions.find(r=>r.id===rid),file=path.join(content,'people/'+p.id+'.md'),raw=await readFile(file,'utf8'),end=raw.indexOf('\n---',4)+4,edges=region?.edges.filter(e=>e.a===p.name||e.b===p.name)||[];const lead=region?`\n\n<div class="atlas-person-context"><span class="lore-kicker">${H(region.title.split(' · ')[0])}에서 함께 읽기</span><a href="${url('/regions/'+rid+'.html')}">${H(region.question)} →</a>${edges.length?relations({...region,edges}):''}${p.id==='1304'?`<a class="lore-more" href="${url('/regions/jinzhou.html#events')}">금희가 시간 제어를 이어받기까지 →</a>`:''}</div>`:'';const sources=index.entries.filter(e=>String(e.role_id)===p.id&&['profile','stories','goods'].includes(e.chunk));const bottom=`<section class="atlas-evidence"><h2>이 페이지의 원문 자료</h2><p class="atlas-caption">위에 수록한 소개·기록·이야기·소장품의 원문입니다. 자료별 본문과 출처를 확인할 수 있습니다.</p><div class="lore-source-list">${sources.map(e=>`<a href="${url(e.page)}"><small>${H(e.category_label)}</small><strong>${H(e.title)}</strong></a>`).join('')}</div></section>`;await writeFile(file,raw.slice(0,end)+lead+atlas.factions.filter(c=>c.roles.includes(p.id)).map(c=>`<div class="atlas-person-context"><a href="${url('/factions/'+c.id+'.html')}">${H(c.title)}의 구성과 인물별 발언 →</a></div>`).join('')+raw.slice(end)+'\n'+bottom);}
 let guide='# 명조 세계관 설정집\n\n지역·인물·세계의 큰 설정을 관계와 사건, 원문으로 이어 읽습니다.\n\n';
 for(const [name,group,cs] of [['세력과 위협','factions',atlas.factions],['지역','regions',atlas.regions],['수호신','sentinels',atlas.sentinels],['세계관의 큰 설정','cosmology',atlas.cosmology]]){guide+='## '+name+'\n\n';for(const c of cs){guide+='### '+c.title+'\n\n**질문:** '+c.question+'\n\n'+c.summary+'\n\n';for(const s of model(c).sections){guide+='#### '+s.title+'\n\n';for(const item of s.items)guide+=item.text+'\n\n'+item.evidence.map(e=>'['+e.title+'](https://mizan0515.github.io'+e.url+')').join(' · ')+'\n\n';}for(const e of c.edges)guide+='- '+e.a+' → **'+e.verb+'** → '+e.b+': '+e.reason+'\n';if(c.timeline){guide+='\n**'+c.timeline.title+'**\n\n';c.timeline.items.forEach((e,i)=>{guide+=(i+1)+'. **'+e.title+'** — '+e.text+'\n';});}guide+='\n[화면에서 관계·원문 함께 읽기](https://mizan0515.github.io'+base+'/'+group+'/'+c.id+'.html)\n\n';}}
 await writeFile(path.join(site,'settings/world-guide.md'),guide);
 console.log(JSON.stringify({atlasEvidence:'PASS',regions:atlas.regions.length,sentinels:atlas.sentinels.length,conceptClusters:atlas.cosmology.length,relations:atlas.regions.reduce((n,c)=>n+c.edges.length,0)}));
}
