import {paragraphRuns,readingMedia,createReadingKit} from '../src/lib/reading-kit/render.mjs';
import {sourceLinkAttributes,htmlAttributes,sourceLink as renderSourceLink,readerFrame,readerDisclosure} from '../src/lib/reading-kit/reader.mjs';
import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import crypto from 'node:crypto';
import {generateAtlas} from './generate-atlas.mjs';
const source=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),site=path.dirname(source),data=path.join(site,'settings'),content=path.join(source,'src/content/docs'),base='/wuwa-quests';
const read=name=>readFile(path.join(data,name),'utf8').then(JSON.parse);
const manifest=await read('manifest.json');
for(const [name,sha] of Object.entries(manifest.files)){const bytes=await readFile(path.join(data,name));const input=manifest.hash_normalization?.[name]==='lf'?bytes.toString('utf8').replace(/\r\n/g,'\n'):bytes;if(crypto.createHash('sha256').update(input).digest('hex')!==sha)throw Error('Setting input changed: '+name);}
const book=await read('editorial.json'),index=await read('index.json'),records={};
const originalCurated=new Set(Object.keys(index.curated_sources));
for(const name of await readdir(data))if(name.startsWith('records-'))Object.assign(records,await read(name));
const entries=new Map(index.entries.map(e=>[e.id,e])),chapters=new Map(book.chapters.map(c=>[c.id,c])),people=new Map(index.characters.map(c=>[c.id,c]));
// Encode source line endings inside HTML so Markdown cannot turn them into paragraphs.
const H=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])).replace(/ +(?=\r?\n|$)/g,spaces=>'&#32;'.repeat(spaces.length)).replace(/\r/g,'&#13;').replace(/\n/g,'&#10;');
const canonical=id=>index.aliases[id]||id,entry=id=>entries.get(canonical(id));
const sourceLink=(id,field='')=>{const e=entry(id);if(e.page.startsWith('/library.html#')){const slug=crypto.createHash('sha256').update(e.id).digest('hex').slice(0,16);e.page='/sources/'+slug+'.html';index.curated_sources[e.id]=slug;}return base+e.page+(field?'#field-'+encodeURIComponent(field):'');};
const imageManifest=JSON.parse(await readFile(path.join(source,'public/game-images/provenance.json'),'utf8'));
const libraryScriptVersion=crypto.createHash('sha256').update((await readFile(path.join(source,'public/lore/library.js'),'utf8')).replace(/\r\n/g,'\n')).digest('hex').slice(0,12);
const monsterImages=new Map([...(imageManifest.monsters||[]),...(imageManifest.geography||[])].map(m=>[m.sourceId,m]));
for(const monster of monsterImages.values())sourceLink(monster.sourceId);
const sourceMedia=id=>{const m=monsterImages.get(id);if(!m)return '';const im=m.images.geography||m.images.bossBanner||m.images.icon;return readingMedia([{...im,alt:m.name+'의 게임 도감 이미지',caption:'게임 도감 이미지 · '+m.name,sourceUrl:base+'/game-images/provenance.json'}]);};
const cite=r=>`<a ${htmlAttributes(sourceLinkAttributes({reading:true}))} href="${H(r.quest_id?base+'/quests/'+r.quest_id+'.html#scene-'+r.scene:sourceLink(r.id,r.field))}">${H(r.label||r.title)} <span aria-hidden="true">↗</span></a>`;
const refs=rs=>`<div class="lore-citations" data-pagefind-ignore>${rs.map(cite).join('')}</div>`;
const sourceEvidence=r=>{
 const row=records[canonical(r.id)],value=row?.values.find(v=>v.field===r.field&&v.status==='OK');
 if(!value||crypto.createHash('sha256').update(value.raw).digest('hex')!==r.source_text_sha256)throw Error('Editorial evidence changed: '+r.id+' / '+r.field);
 if(r.quote&&!value.text.includes(r.quote))throw Error('Editorial quotation differs: '+r.id+' / '+r.field);
 // Stored overview excerpts can end with an editorial ellipsis. The proof shows
 // the actual preserved field instead of presenting that abbreviation as a quote.
 const quote=r.quote||(r.excerpt&&value.text.includes(r.excerpt)?r.excerpt:value.text);
 return {id:'editorial-'+crypto.createHash('sha256').update(canonical(r.id)+'|'+r.field).digest('hex').slice(0,16),title:r.label||r.title||entry(r.id).title,url:sourceLink(r.id,r.field),quote,...(r.speaker?{speaker:r.speaker}:{})};
};
const evidenceFor=rs=>[...new Map(rs.map(r=>[canonical(r.id)+'|'+r.field,r])).values()].map(sourceEvidence);
const kit=createReadingKit({inline:H,evidence:items=>items.map(r=>`<span class="rw-attribution">원문 인용${r.speaker?' · '+H(r.speaker):''}</span><blockquote>${H(r.quote)}</blockquote>${renderSourceLink(r.url,r.title+' ↗',{reading:true})}`).join('')});
const clean=s=>s.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/?(?:te|color|size|b|i|u|ano|s)(?:[=\s][^>]*)?>/g,'');
function linked(raw){let out='',last=0;for(const m of raw.matchAll(/<te\s+href[=\s]+["']?(\d+)["']?\s*>(.*?)<\/te>/gs)){out+=H(clean(raw.slice(last,m.index)));const i=book.concepts.findIndex(c=>c.term_id===m[1]);out+=i>=0?`<a href="${base}/concepts/${i}.html">${H(clean(m[2]))}</a>`:H(clean(m[2]));last=m.index+m[0].length;}return out+H(clean(raw.slice(last)));}
const labels={country:'출신',influence:'소속',info:'인물 소개',talent_name:'공명 능력',talent_document:'공명 기록',talent_certification:'안정성 기록',content:'본문',background:'배경',description:'설명',usage:'용도',obtained_description:'획득 설명',attributes_description:'제작·속성 설명',discovered_description:'발견 후 생태',undiscovered_description:'발견 전 설명',place:'서식 지역',region:'지역',sub_name:'설정 분류'};
function fields(row,only=null,prefix=''){const used=new Set(),values=row.values.filter(v=>!['name','title','type','birthday','sex'].includes(v.field)&&(!only||only.includes(v.field)));return values.map(v=>{if(v.status==='OK'&&used.has(v.raw))return '';if(v.status==='OK')used.add(v.raw);const aliases=v.status==='OK'?values.filter(a=>a!==v&&a.status==='OK'&&a.raw===v.raw):[];const body=`${aliases.map(a=>`<span id="field-${H(prefix+a.field)}"></span>`).join('')}<h2>${[v,...aliases].map(a=>H(labels[a.field]||a.field)).join(' · ')}</h2>${v.status==='OK'?`<div class="lore-source-text rw-original">${paragraphRuns(v.raw).map(p=>`<p>${linked(p.text)}</p>`).join('')}</div>`:`<p class="lore-muted">${v.status==='EMPTY'?'원문이 비어 있습니다.':v.status==='NO_REFERENCE'?'원문 참조가 없습니다.':'한국어 원문 키를 찾지 못했습니다.'}</p>`}${readerDisclosure('원문·출처 확인',`<dl>${[v,...aliases].map(a=>`<dt>${H(labels[a.field]||a.field)} 키</dt><dd>${H(a.text_id||'없음')}</dd><dt>언어 DB</dt><dd>${H(a.locale_db||'미확인')}</dd>`).join('')}<dt>상태</dt><dd>${H(v.status)}</dd></dl><pre>${H(v.raw)}</pre>`,{className:'lore-provenance',attributes:{'data-pagefind-ignore':'all'}})}`;return `<section class="lore-field" id="field-${H(prefix+v.field)}">${readerFrame(body,{variant:'original',className:'lore-field-reader'})}</section>`;}).join('');}
async function doc(slug,title,body,description='',toc=true,pagefind=true){await mkdir(path.dirname(path.join(content,slug+'.md')),{recursive:true});await writeFile(path.join(content,slug+'.md'),`---\ntitle: ${JSON.stringify(title)}\ndescription: ${JSON.stringify(description||title+' · 근거 원문과 함께 읽는 명조 설정집')}\ntableOfContents: ${toc}\npagefind: ${pagefind}\n---\n\n${body}\n`);}
const chapterDirectory=cs=>kit.directory(cs.map(c=>({name:c.title,summary:[c.number+' · '+c.subtitle,c.summary,c.question].join('\n'),url:base+'/world/'+c.id+'.html'})));
const related=ids=>chapterDirectory(ids.map(id=>chapters.get(id)).filter(Boolean));
let overview=`<div class="lore-intro"><p class="lore-kicker">서로 이어 읽는 세계관</p><p class="lore-statement">흩어진 설정을,<br>하나의 세계로 읽다.</p><p class="lore-lead">주파수에서 한 사람의 삶으로, 도시의 신앙에서 생존의 기술로.<br>자료 사이의 관계를 따라 읽는 일곱 개의 해설입니다.</p><div class="lore-actions"><a class="lore-primary" href="${base}/world/frequency.html">주파수부터 읽기 <span aria-hidden="true">→</span></a><a href="${base}/people.html">인물 찾기</a><a href="${base}/concepts.html">용어 살펴보기</a></div></div>`;
for(const [title,description,ids] of [['세계의 법칙','재앙의 흔적이 힘과 감각이 되는 과정',['frequency','resonance']],['도시와 문명','사람들은 같은 세계를 어떻게 다르게 살아가는가',['city','shore','rinascita','raha']],['기록을 읽는 시선','서식지의 관계와 기록 속 서술 차이',['ecology']]])overview+=`<section class="lore-group"><div class="lore-group-heading"><h2>${title}</h2><p>${description}</p></div>${related(ids)}</section>`;
overview+=`<div class="lore-note"><strong>원문 연결</strong>은 자료에 적힌 내용, <strong>읽는 관점</strong>은 자료 사이의 해석입니다. 서술 차이와 확인되지 않은 관계는 그대로 남겼습니다.</div><div class="lore-actions lore-download"><a href="${base}/settings/world-guide.md" download>전체 해설 문서 ↓</a><a href="${base}/library.html">원문 보관함 ↗</a></div>`;
await doc('world','세계관 설정집',overview,'인물·문서·지역·생태의 관계를 엮어 읽는 세계관 해설',false);
const citedFields=[];
for(const c of book.chapters){
 const chapterRefs=[...new Map(c.sections.flatMap(s=>s.paragraphs.flatMap(p=>p.refs)).concat(c.caution?.refs||[]).map(r=>[r.id+'|'+r.field,r])).values()];
 const chapterEvidence=evidenceFor(chapterRefs);
 let body=`<div class="lore-article-intro"><p class="lore-kicker">${c.number} · ${H(c.subtitle)}</p><p class="lore-question">${H(c.question)}</p><p class="lore-lead">${H(c.summary)}</p></div>${kit.process(c.flow.map(s=>({title:s.title,text:s.detail,kind:'inference',evidence:chapterEvidence})),{kind:'reading',label:'함께 읽는 순서'})}`;
 for(const [i,s] of c.sections.entries()){body+=kit.section({id:'editorial-'+c.id+'-section-'+i,title:s.title,items:s.paragraphs.map(p=>({text:p.text,kind:p.kind==='reading'?'inference':'fact',evidence:evidenceFor(p.refs)}))});for(const p of s.paragraphs)citedFields.push(...p.refs);}
 if(c.caution){body+=kit.comparison([{title:c.caution.title,text:c.caution.text,kind:'inference',evidence:evidenceFor(c.caution.refs)}]);citedFields.push(...c.caution.refs);}
 // Quotes make two conflicting primary records inspectable without guessing a correction.
 if(c.id==='evidence'||c.id==='resonance')body+=kit.comparison([
  {id:'인물_프로필_공명기록:favorroleinfo:1102',field:'talent_document',title:'공명 검사 기록',quote:'괴상한 폭설 중 잔상에 의해 오른쪽 눈의 주파수가 침식되어 시각에 이상이 생김과 동시에 어빌리티가 각성되었다.'},
  {id:'인물_이야기:favorstory:110202',field:'content',title:'인물 이야기 · 갑작스러운 눈',quote:'잔상은 그녀의 생명을 빼앗지 않고 그녀의 왼쪽 눈을 침식하였고 잔향의 주파수는 기적처럼 새로운 눈을 형성하였다.'}
 ].map(r=>({title:r.title,text:r.quote,kind:'fact',evidence:[sourceEvidence({...r,label:r.title,source_text_sha256:crypto.createHash('sha256').update(records[r.id].values.find(v=>v.field===r.field).raw).digest('hex')})]})));
 body+=`\n\n## 함께 읽는 인물과 개념\n\n<div class="lore-pills">${c.roles.map(id=>people.get(id)).filter(Boolean).map(p=>`<a href="${base}/people/${p.id}.html">${H(p.name)}</a>`).join('')}${book.concepts.map((term,i)=>({term,i})).filter(x=>x.term.term_id&&c.terms.includes(x.term.term_id)).map(x=>`<a href="${base}/concepts/${x.i}.html">${H(x.term.name)}</a>`).join('')}</div>`;
 if(c.quest_links?.length){body+=`\n\n## 대사에서 이어 읽기\n\n<p class="lore-muted">같은 인물·용어가 실제 대사에 등장하는 퀘스트입니다. 언급의 연결이며 같은 사건이라는 뜻은 아닙니다.</p>${kit.directory(c.quest_links.map(q=>({name:q.title,summary:q.terms.join(' · ')+'\n'+q.snippet,url:base+'/quests/'+q.id+'.html'})))}`;}
 body+=`\n\n## 이 질문에서 이어지는 설정\n\n${related(c.related)}`;
 body+=`<section class="atlas-evidence"><h2>이 페이지의 원문 근거</h2><p class="atlas-caption">실제 텍스트에서 확인한 자료입니다. 각 링크는 해당 원문 본문으로 이동합니다.</p>${chapterRefs.map(r=>readerDisclosure(r.label,`<blockquote>${H(sourceEvidence(r).quote)}</blockquote>${refs([r])}`,{className:'editorial-proof'})).join('')}</section>`;
 await doc('world/'+c.id,c.title,body);
}
for(const r of [...citedFields,...book.concepts.map(c=>c.ref)]){const row=records[canonical(r.id)],v=row.values.find(v=>v.field===r.field);if(!v||v.status!=='OK'||crypto.createHash('sha256').update(v.raw).digest('hex')!==r.source_text_sha256)throw Error('Invalid interpretation evidence: '+r.id);if(r.quote&&!v.text.includes(r.quote))throw Error('Quotation mismatch');}
const values=(row,field)=>row.values.find(v=>v.field===field&&v.status==='OK')?.text||'';
for(const c of index.characters){const rows=index.entries.filter(e=>String(e.role_id)===c.id),profile=rows.find(e=>e.chunk==='profile');let body=`<div class="lore-profile-meta">${H(c.country)} <span aria-hidden="true">·</span> ${H(c.influence)}</div>${c.chapters.length?`<p class="lore-kicker">이 인물의 설정을 엮어 읽는 해설</p>${related(c.chapters)}`:''}`;
 if(profile)body+=fields(records[profile.id],['info','talent_name','talent_document','talent_certification']);
 for(const [chunk,title] of [['stories','인물 이야기'],['goods','소장품']]){body+=`\n\n## ${title}\n\n`;for(const e of rows.filter(e=>e.chunk===chunk)){const row=records[e.id];body+=`<details class="lore-story"><summary>${H(e.title.replace(c.name+' · ',''))}</summary><div class="lore-story-body">${fields(row,null,e.chunk+'-'+row.entry_id+'-')}${renderSourceLink(base+e.page,'이 자료의 원문·출처 ↗',{reading:true})}</div></details>\n\n`;}}
 body+=`\n\n## 음성 대사와 다른 자료\n\n<div class="lore-actions"><a href="${base}/library.html#/library?role=${c.id}&amp;category=${encodeURIComponent('인물_음성대사')}">음성 대사 ${c.counts.voice||0}개 읽기 ↗</a><a href="${base}/index.html?q=${encodeURIComponent(c.name)}">이름으로 퀘스트 제목 찾기 ↗</a></div><p class="lore-note">프로필·공명 기록, 인물 이야기, 소장품, 음성 대사를 자료 종류별로 읽을 수 있습니다.</p>`;
 await doc('people/'+c.id,c.name,body);
}
const characterCard=c=>`<a class="lore-person-card" href="${base}/people/${c.id}.html" data-name="${H(c.name)}" data-country="${H(c.country)}"><h3>${H(c.name)}</h3><p>${H(c.influence||c.country||'소속 미확인')}</p><small>이야기 ${c.counts.stories||0} · 소장품 ${c.counts.goods||0}</small>${c.chapters.length?'<span class="lore-person-related">관련 해설 '+c.chapters.length+'편 ↗</span>':''}</a>`;
await doc('people','인물별 설정',`<p class="lore-lead">검사 기록과 이야기, 소장품과 대사를 한 사람의 삶으로 함께 읽습니다.</p><div class="lore-people-controls" role="search"><label for="lore-person-q">인물 이름<input type="search" id="lore-person-q" placeholder="예: 산화, 파수인" autocomplete="off"></label><p id="lore-person-count" role="status" aria-live="polite">${index.characters.length}개 인물 묶음</p></div><div class="lore-person-grid">${index.characters.map(characterCard).join('')}</div><p id="lore-person-empty" hidden>찾는 인물이 없습니다. 이름을 짧게 바꿔보세요.</p><p class="lore-note">이 목록은 원자료에 수록된 인물 항목을 기준으로 합니다.</p><script src="${base}/lore/people.js" defer></script>`,'프로필·공명 검사·이야기·소장품을 함께 읽는 인물별 자료',false,false);
await doc('concepts','개념과 용어',`<p class="lore-lead">같은 말이 등장하는 다른 자료들을 이어 읽습니다. 먼저 읽을 핵심 개념 ${book.concepts.length}개를 골랐습니다.</p>${kit.directory(book.concepts.map((c,i)=>({name:c.name,summary:c.summary,url:base+'/concepts/'+i+'.html'})))}`,'근거와 함께 읽는 '+book.concepts.length+'개 핵심 개념',false);
for(const [i,c] of book.concepts.entries()){const matches=c.term_id?index.entries.filter(e=>e.group!=='technical'&&e.term_ids.includes(c.term_id)):[];await doc('concepts/'+i,c.name,`<p class="lore-lead">${H(c.summary)}</p>${readerFrame(`<blockquote>${H(c.ref.excerpt)}</blockquote>${refs([c.ref])}`,{variant:'original',className:'concept-original'})}\n\n## 같은 용어를 언급한 원문\n\n<p class="lore-muted">${c.term_id?'이 용어의 게임 본문 링크가 포함된 자료입니다.':'위에 제시한 원문을 중심으로 이 개념을 설명합니다.'}</p>${kit.directory(matches.slice(0,10).map(e=>({name:e.title,summary:e.category_label+'\n'+e.excerpt,url:base+e.page})))}${matches.length>10?`<a class="lore-more" href="${base}/library.html#/library?term=${c.term_id}">관련 원문 ${matches.length}개 모두 보기 ↗</a>`:''}`);}
for(const [id,slug] of Object.entries(index.curated_sources)){const e=entry(id),row=records[id];await doc('sources/'+slug,e.title,`<p class="lore-kicker">${H(e.category_label)}</p>${e.role_id?`<a class="lore-more" href="${base}/people/${e.role_id}.html">${H(e.role_name)}의 자료 함께 읽기 ↗</a>`:''}${e.chapters.length?related(e.chapters):''}${sourceMedia(id)}${fields(row)}<details class="lore-provenance" data-pagefind-ignore="all"><summary>원자료 기록 정보</summary><dl><dt>자료 ID</dt><dd>${H(row.entry_id)}</dd><dt>테이블</dt><dd>${H(row.db+' / '+row.table)}</dd></dl></details>${e.related_item?`<a class="lore-more" href="${H(base+entry(e.related_item).page)}">문서가 연결한 아이템 읽기 ↗</a>`:''}`);}
await doc('library','원문 보관함',`<div id="lore-reader" data-base="${base}" tabindex="-1"><p role="status">원문 목록을 불러오는 중입니다.</p></div><noscript><p>원문 검색에는 JavaScript가 필요합니다. <a href="${base}/world.html">세계관 해설</a>과 <a href="${base}/people.html">인물 자료</a>는 바로 읽을 수 있습니다.</p></noscript><script src="${base}/lore/library.js?v=${libraryScriptVersion}" defer></script>`,'문서·지역·인물·생태·장비 원문을 찾아 읽는 보관함',false,false);
const sidebar=JSON.parse(await readFile(path.join(source,'generated-sidebar.json'),'utf8'));
sidebar.splice(1,0,{label:'세계관 설정집',link:'/world.html'},{label:'인물별 설정',link:'/people.html'},{label:'개념과 용어',link:'/concepts.html'},{label:'원문 보관함',link:'/library.html'},{label:'이어 읽는 설정',collapsed:true,items:book.chapters.map(c=>({label:c.title,link:'/world/'+c.id+'.html'}))});
await writeFile(path.join(source,'generated-sidebar.json'),JSON.stringify(sidebar));
await generateAtlas({site,content,book,index,records,doc,H,refs,related});
// Every newly cited source has its own stable HTML document and field anchor.
for(const [id,slug] of Object.entries(index.curated_sources)){if(originalCurated.has(id))continue;const e=entry(id),row=records[id];await doc('sources/'+slug,e.title,`<p class="lore-kicker">${H(e.category_label)}</p>${sourceMedia(id)}${fields(row)}`,e.title+' · 원문 기록');}

await mkdir(path.join(source,'public/settings'),{recursive:true});for(const name of await readdir(data))await copyFile(path.join(data,name),path.join(source,'public/settings',name));
await writeFile(path.join(source,'public/settings/curated-sources.json'),JSON.stringify({schema:'wuwa-curated-sources.v1',inputIndexSha256:manifest.files['index.json'],sources:index.curated_sources}));
const about=path.join(content,'about.md');await writeFile(about,(await readFile(about,'utf8'))+`\n\n## 세계관 설정집\n\n[세계관 설정집](${base}/world.html)은 인물 검사 기록·이야기·소장품·문서·지역·생태·무기 설명을 실제로 읽고 관계를 엮은 비공식 해설입니다. ‘원문 연결’과 ‘읽는 관점’을 구분하고 서술 차이를 보존했습니다. 원자료 ${index.source_records}개를 유지하고, 동일 종류·인물에서 모든 원문 읽기 필드가 같은 기록을 접어 ${index.reading_entries}개 읽기 항목으로 보여줍니다. 캐시 자료의 관찰 날짜는 2026-10-07이며 실제 클라이언트 버전과 최초 출시 시점은 미확인입니다. 이번에 새 클라이언트를 추출했다는 뜻은 아닙니다.\n\n상단 검색은 퀘스트·해설·인물 및 선택된 근거 원문을 함께 찾습니다. 전체 설정 원문 ${index.reading_entries}개를 본문으로 찾으려면 [원문 보관함](${base}/library.html)에서 ‘본문까지’를 선택합니다. 모든 기록에 개별 해석을 붙였다는 뜻은 아닙니다.\n`);
console.log(JSON.stringify({loreChapters:book.chapters.length,people:64,concepts:16,curatedSources:Object.keys(index.curated_sources).length,readingEntries:8668,evidenceSha256:'PASS',localPaths:'EXCLUDED'}));
